import sqlalchemy as sa

from alembic import op

revision = "0001_foundation"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hotels",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_hotel_id", sa.String(length=128), nullable=False),
        sa.Column("hotel_name", sa.String(length=300), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("default_currency", sa.String(length=3), nullable=True),
        sa.Column("official_url", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_hotel_id"),
    )
    op.create_index(op.f("ix_hotels_city"), "hotels", ["city"], unique=False)
    op.create_index(op.f("ix_hotels_provider"), "hotels", ["provider"], unique=False)
    op.create_table(
        "provider_status",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_success", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("blocked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metrics_date", sa.Date(), nullable=False),
        sa.Column("requests_today", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("average_latency", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.PrimaryKeyConstraint("provider"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "watchlists",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "crawl_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("hotel_id", sa.String(length=36), nullable=True),
        sa.Column("check_in", sa.Date(), nullable=True),
        sa.Column("check_out", sa.Date(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("dedupe_key", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=36), nullable=True),
        sa.Column("error_type", sa.String(length=40), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_job_due", "crawl_jobs", ["status", "scheduled_at"], unique=False)
    op.create_index(
        "uq_live_job",
        "crawl_jobs",
        ["dedupe_key"],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING','QUEUED','RUNNING')"),
        sqlite_where=sa.text("status IN ('PENDING','QUEUED','RUNNING')"),
    )
    op.create_table(
        "price_alerts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("hotel_id", sa.String(length=36), nullable=False),
        sa.Column("offer_key", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("anomaly_score", sa.Integer(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("verification_job_id", sa.String(length=36), nullable=True),
        sa.Column("dedupe_key", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index(op.f("ix_price_alerts_hotel_id"), "price_alerts", ["hotel_id"], unique=False)
    op.create_index(op.f("ix_price_alerts_offer_key"), "price_alerts", ["offer_key"], unique=False)
    op.create_table(
        "price_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("hotel_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("offer_key", sa.String(length=64), nullable=False),
        sa.Column("check_in", sa.Date(), nullable=False),
        sa.Column("check_out", sa.Date(), nullable=False),
        sa.Column("room_type", sa.String(length=300), nullable=True),
        sa.Column("room_code", sa.String(length=128), nullable=True),
        sa.Column("rate_name", sa.String(length=300), nullable=True),
        sa.Column("rate_code", sa.String(length=128), nullable=True),
        sa.Column("cash_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("tax", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("total_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("points_price", sa.Integer(), nullable=True),
        sa.Column("refundable", sa.Boolean(), nullable=True),
        sa.Column("breakfast_included", sa.Boolean(), nullable=True),
        sa.Column("member_rate", sa.Boolean(), nullable=True),
        sa.Column("availability", sa.Boolean(), nullable=False),
        sa.Column("adults", sa.Integer(), nullable=False),
        sa.Column("rooms", sa.Integer(), nullable=False),
        sa.Column("price_basis", sa.String(length=32), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("raw_response_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "offer_key"),
    )
    op.create_index(
        "ix_history_hotel_date_time", "price_history", ["hotel_id", "check_in", "captured_at"], unique=False
    )
    op.create_index(op.f("ix_price_history_captured_at"), "price_history", ["captured_at"], unique=False)
    op.create_index(op.f("ix_price_history_hotel_id"), "price_history", ["hotel_id"], unique=False)
    op.create_index(op.f("ix_price_history_offer_key"), "price_history", ["offer_key"], unique=False)
    op.create_table(
        "price_statistics",
        sa.Column("offer_key", sa.String(length=64), nullable=False),
        sa.Column("hotel_id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("median_7d", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("median_30d", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("median_90d", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("historical_low", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("historical_high", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("local_date_median", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("neighbor_date_median", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("offer_key"),
    )
    op.create_index(op.f("ix_price_statistics_hotel_id"), "price_statistics", ["hotel_id"], unique=False)
    op.create_table(
        "rates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("hotel_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("offer_key", sa.String(length=64), nullable=False),
        sa.Column("check_in", sa.Date(), nullable=False),
        sa.Column("check_out", sa.Date(), nullable=False),
        sa.Column("room_type", sa.String(length=300), nullable=True),
        sa.Column("room_code", sa.String(length=128), nullable=True),
        sa.Column("rate_name", sa.String(length=300), nullable=True),
        sa.Column("rate_code", sa.String(length=128), nullable=True),
        sa.Column("cash_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("tax", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("total_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("points_price", sa.Integer(), nullable=True),
        sa.Column("refundable", sa.Boolean(), nullable=True),
        sa.Column("breakfast_included", sa.Boolean(), nullable=True),
        sa.Column("member_rate", sa.Boolean(), nullable=True),
        sa.Column("availability", sa.Boolean(), nullable=False),
        sa.Column("adults", sa.Integer(), nullable=False),
        sa.Column("rooms", sa.Integer(), nullable=False),
        sa.Column("price_basis", sa.String(length=32), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("raw_response_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("offer_key"),
    )
    op.create_index(op.f("ix_rates_captured_at"), "rates", ["captured_at"], unique=False)
    op.create_index(op.f("ix_rates_hotel_id"), "rates", ["hotel_id"], unique=False)
    op.create_index(op.f("ix_rates_offer_key"), "rates", ["offer_key"], unique=False)
    op.create_table(
        "notification_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("alert_id", sa.String(length=36), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("dedupe_key", sa.String(length=100), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["price_alerts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_logs")
    op.drop_index(op.f("ix_rates_offer_key"), table_name="rates")
    op.drop_index(op.f("ix_rates_hotel_id"), table_name="rates")
    op.drop_index(op.f("ix_rates_captured_at"), table_name="rates")
    op.drop_table("rates")
    op.drop_index(op.f("ix_price_statistics_hotel_id"), table_name="price_statistics")
    op.drop_table("price_statistics")
    op.drop_index(op.f("ix_price_history_offer_key"), table_name="price_history")
    op.drop_index(op.f("ix_price_history_hotel_id"), table_name="price_history")
    op.drop_index(op.f("ix_price_history_captured_at"), table_name="price_history")
    op.drop_index("ix_history_hotel_date_time", table_name="price_history")
    op.drop_table("price_history")
    op.drop_index(op.f("ix_price_alerts_offer_key"), table_name="price_alerts")
    op.drop_index(op.f("ix_price_alerts_hotel_id"), table_name="price_alerts")
    op.drop_table("price_alerts")
    op.drop_index(
        "uq_live_job",
        table_name="crawl_jobs",
        postgresql_where=sa.text("status IN ('PENDING','QUEUED','RUNNING')"),
        sqlite_where=sa.text("status IN ('PENDING','QUEUED','RUNNING')"),
    )
    op.drop_index("ix_job_due", table_name="crawl_jobs")
    op.drop_table("crawl_jobs")
    op.drop_table("watchlists")
    op.drop_table("settings")
    op.drop_table("provider_status")
    op.drop_index(op.f("ix_hotels_provider"), table_name="hotels")
    op.drop_index(op.f("ix_hotels_city"), table_name="hotels")
    op.drop_table("hotels")
    # ### end Alembic commands ###
